### ISSUE TITLE
dashboard

### ISSUE THREAD

**Issue by cryslivino** [tegcommerce/tegcommerce-demo#24]
when you access the panel, you will find

store section - to see the store

product section - to manage products

page section - to manage pages

plugins section - to manage plugins

theme selection - to manage themes

users section - to manage users

**Comment by devfelipemonteiro** [comment]
requisite-functional-admin-user-dashboard-theme-section

**Comment by devfelipemonteiro** [comment]
requisite-functional-admin-user-dashboard-user-section
